import { Inter } from 'next/font/google'
import { Caprasimo } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })
const caprasimo = Caprasimo({
  subsets: ['latin'],
  display: 'swap',
  weight: '400'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={caprasimo.className}>{children}</body>
    </html>
  )
}
